### ISSUE TITLE
cannot authenticate

### ISSUE THREAD

**Issue by jmgunn87** [codeswholesale/codeswholesale-sdk-php#1]
I have replaced the list products example with my client id and secret but it throws an exception when i try to connect.

``` php
Fatal error: Uncaught exception 'fkooman\OAuth\Client\TokenResponseException' with message 'missing field 'access_token'' in 
codeswholesale-sdk-php/vendor/fkooman/php-oauth-client/src/fkooman/OAuth/Client/TokenResponse.php on line 33

fkooman\OAuth\Client\TokenResponseException: missing field 'access_token' in 
codeswholesale-sdk-php/vendor/fkooman/php-oauth-client/src/fkooman/OAuth/Client/TokenResponse.php on line 33
```

When I **print_r** inside that function I see that the response from the server is this,

``` php
Array
(
    [error] => unauthorized
    [error_description] => No client with requested id: <my cid>
)
```

**Comment by n321203** [comment]
Can you provide a curl example or just describe how the request to buy a code should look?

I have successfully authorized and got a token. 
But posting to 
https://sandbox.codeswholesale.com/v1/orders?productId=PRODUCTID
with the token in the headers always gives me a status:500, code:90001 error.

Should the request be a POST or Get?
