### ISSUE TITLE
Retrieving ProductId from preorder postback 

### ISSUE THREAD

**Issue by rchoffardet** [codeswholesale/codeswholesale-sdk-php#10]
Hello,

I'm using your SDK and I'm seeking to retrieve the productId from `$productOrdered` as `$productOrdered = $client->receiveProductOrdered();` so i'll be able to associate these two and gives codes where it needs to go.

Could you help me ?

**Comment by codeswholesale** [comment]
I'll take a look at it, sorry for such long response

**Comment by codeswholesale** [comment]
Hey @rchoffardet,

I am really sorry for the big delay on our side. Now that we have moved from API v1 to v2, I'm back with the right answer to you! You will receive an order ID for the preorder postback, which will enable you to send a request to the OrderHistory endpoint. Here, you will find a lot of information about the previous orders. 

Remember to take a quick look at our recent update and features! 

Cheers!
