### ISSUE TITLE
unauthorized accessing sandbox api with client_id and client_secret

### ISSUE THREAD

**Issue by 1mike12** [codeswholesale/codeswholesale-sdk-php#13]
It never specifies in the documentation to only use the public credentials. I can use `ff72ce315d1259e822f47d87d02d261e` and `$2a$10$E2jVWDADFA5gh6zlRVcrlOOX01Q/HJoT6hXuDMJxek.YEo.lkO2T6` fine, but as soon as I substitute my own keys to access sandbox, it stops working. Is that supposed to happen?

**Comment by codeswholesale** [comment]
Hello @1mike12 

For sandbox connection, you should use credentials provided in PHP-SDK library. 
To connect directly to LIVE Endpoint you should generate your custom credentials under REST API tab in app.codeswholesale.com.
