### ISSUE TITLE
(PRESTASHOP)Status: Disconnected, Reason: The access token that you've provided is not valid, check your credentials or endpoint.

### ISSUE THREAD

**Issue by TheCrazyToby** [codeswholesale/codeswholesale-sdk-php#14]
I keep getting this error when i save my configuration with the Prestashop plugin. 

![image](https://cloud.githubusercontent.com/assets/5989118/20249335/b5226a20-a9f7-11e6-9582-acf1aa838458.png)

I know I have entered the right credentials.

**Comment by codeswholesale** [comment]
Hello @TheCrazyToby 
Please contact with our devteam.codeswholesale. 
An issue is not related directly to PHP-SDK.
