### ISSUE TITLE
"No payment module is installed"

### ISSUE THREAD

**Issue by GaetanSsfm** [codeswholesale/codeswholesale-sdk-php#16]
Hello, I have another problem with your Module, when I activate that and he's work correct in back-post, on the store when I try to command a game, and would like to pay I have this error, I have Paypal module installed already and he's working perfect when I disable codeswholesale. Look at this pick : 
![capture](https://cloud.githubusercontent.com/assets/4027268/20936651/a8767566-bbe3-11e6-98ac-f88efaba26de.PNG)
Work on prestashop 1.6.1.10 and the example is for DLC Euro Truck Vive la France! 

Bests.

**Comment by codeswholesale** [comment]
In module cases, please contact our devteam@codeswholesale.com
