### ISSUE TITLE
The module stopped refreshing the price and the quantity

### ISSUE THREAD

**Issue by TiborPalcpa** [codeswholesale/codeswholesale-sdk-php#17]
After 1-2 month of use the module stopped with updating, 

The Stock and Price post back link is correct but after when I try to send a test request got this error 

![error](https://cloud.githubusercontent.com/assets/24981880/21746205/81b95060-d53d-11e6-9ce1-5d6dbcbef01c.JPG)

**Comment by seruntafad** [comment]
Hi, I have the same problem, some solution?

**Comment by codeswholesale** [comment]
In module cases, please contact our devteam@codeswholesale.com
