### ISSUE TITLE
Client KEY not working

### ISSUE THREAD

**Issue by eltonokada** [codeswholesale/codeswholesale-sdk-php#2]
Hi,

I am using the API, i created a client, but isn't working, i am getting this message on request:

HTTP Status 401 - No client with requested id: 57dc8d53895e4100dd817e090251347d

When using with the sample key from: https://github.com/codeswholesale/codeswholesale-sdk-php

ff72ce315d1259e822f47d87d02d261e

It works.

Really appreciate your help.

Thanks

**Comment by eltonokada** [comment]
I was using the sandbox, so it wasn't working, but now i pointed to live and is fine, so i am closing this.

**Comment by codeswholesale** [comment]
Hey,

We are happy that you solved this issue.

We are always available for you on:
Skype: devteam.codeswholesale,
E-mail: devteam@codeswholesale.com

Best Regards,
DevTeam
