### ISSUE TITLE
Receiving code of type CODE_PREORDER instead of CODE_TEXT (sandbox)

### ISSUE THREAD

**Issue by rchoffardet** [codeswholesale/codeswholesale-sdk-php#25]
Hey,

I'm actually doing improvements to an existing implement of your api.
For unit testing purposes I need to get only text code.

You have a product called "Test with text codes only" with id "ffe2274d-5469-4b0f-b57b-f8d21b09c24c", unfortunately when I try to order it, I receive a preorder, which is not desirable.

**Comment by codeswholesale** [comment]
Hey @rchoffardet,

It is possible to receive such response when code is out of stock. We are going to update stock of products like text/ image to bigger values.

Consider it as good opportunity for validating product stock before request.

Thanks,
CodesWholesale

**Comment by rchoffardet** [comment]
But this is a problem : Unit tests needs to receive the same input everything. This way, they can be use to check if the Unit code works or not. If this item can become out of stock, input varies and this is not good !

**Comment by codeswholesale** [comment]
Your unit tests should not depend on external service. You should mock your implementation of CodesWholesale. All products can be out of stock

**Comment by rchoffardet** [comment]
I wouldn't test your sdk if you had tests, but you don't.
Also you have this four products : 
- "Test pre order product"
- "Test product with high price"
- "Test with image codes only"
- "Test with text codes only"
Wouldn't be great if : 
- the first product were always out of stock but send a postback request with a code inside
- the second product were always in stock with a high price
- the third product were always in stock and would give only image code
- the fourth product were always in stock and would give only text code
I mean, it would match your description at least.

You told me (https://github.com/codeswholesale/codeswholesale-sdk-php/issues/25#issuecomment-346045230) that you were going to update the stock : product is still out of stock

Plus, I asked you to implement a way to avoid preorders (even if out of stock) : https://github.com/codeswholesale/codeswholesale-sdk-php/issues/9
This one one year and an half ago ! You said you'll do it ASAP, I'm still waiting.

**Comment by codeswholesale** [comment]
Hey there,

I am happy to inform you that we released new version of SDK, which supports you previous requirements like avoiding preorders. Take a look at new features here: https://github.com/codeswholesale/codeswholesale-sdk-php/releases/tag/2.0
