### ISSUE TITLE
Retrieve specific product

### ISSUE THREAD

**Issue by Sammyy96** [codeswholesale/codeswholesale-sdk-php#33]
Hi, I think it would be good if you made a function in Client.php for retrieving specific products as your current documentation says you can get specific products instead of all products. A suggestion, something like this_

 ```
 public function getProduct($producctID, array $options = [])
    {
        return $this->dataStore->getResource(
            CodesWholesale::API_VERSION_V2 . '/products/'.$productID,
            CodesWholesale::PRODUCT,
            $options
            );
    }
```

I also would like to say that your current documentation for v2 is not very detailed and fails to point out some things, so those who would like to make their own environment for connecting to your platform instead of using your sdk will have a very hard time doing so.

**Comment by codeswholesale** [comment]
Hey there, 

You can simply get Product by using below function:

 $product = \CodesWholesale\Resource\Product::get($productId);

For more check examples directory, single-product.php.
