### ISSUE TITLE
Possible issues

### ISSUE THREAD

**Issue by Sammyy96** [codeswholesale/codeswholesale-sdk-php#34]
in Client.php you have named something pareOrder... instead of preOrder. Also I can't find the $client->receiveProductOrdered() method in Client.php. It is used in an example so it had me curious..

**Comment by codeswholesale** [comment]
Hey @Sammyy96 

Thanks for writing to us! The language issue has been fixed and also I've deleted the unsupported example, big thanks for you alertness!

Now when our SDK provides connection to API v2.0 you should take a look of our new example: notification-handling.php which provides new way of handling postback's. 

Let me know if you have, any more questions :)
