### ISSUE TITLE
Client error: `POST https://api.codeswholesale.com/v2/orders` resulted in a `400 Bad Request` response: {"status":400,"code":310003,"message":"Cannot complete, too low stock."

### ISSUE THREAD

**Issue by fefrik** [codeswholesale/codeswholesale-sdk-php#41]
Hi, 

After changes in CW API, We are not able to create new order! All our orders ended with error code `400 Bad Request` response: {"status":400,"code":310003,"message":"Cannot complete, too low stock."}

When I call GET /product request, I got correct quantity state, that is similar with CW pricelist, so product is on stock:

```
        $product = \CodesWholesale\Resource\Product::get("https://api.codeswholesale.com/v2/products/" . $link);

        echo "Name: " . $product->getName() . "<br>";
        echo "BuyHref: " . $product->getBuyHref() . "<br>";
        echo "DefaultPrice: " . $product->getDefaultPrice() . "<br>";
        echo "LowestPrice: " . $product->getLowestPrice() . "<br>";
        echo "Quantity: " . $product->getStockQuantity() . "<br>";
```

But when I create order, I got error 400 Bad Request` response: {"status":400,"code":310003,"message":"Cannot complete, too low stock."

```
$createdOrder = \CodesWholesale\Resource\Order::createOrder(
            [
                [
                    "productId" => $product->getProductId(),
                    "quantity" => $orderItem->getCount(),
                ],
            ], null);
```
Please, Can you look on it. We have to handle all orders manually now... :-( 

Thank you

**Comment by officialmmt** [comment]
If you check api you will see there is only one price now.

**Comment by fefrik** [comment]
It seems to be fixed on backend side. Now it works fine.
