### ISSUE TITLE
No possibility to get game cover

### ISSUE THREAD

**Issue by shiftedreality** [codeswholesale/codeswholesale-sdk-php#5]
Please, add  method, returning URL with cover for product

**Comment by codeswholesale** [comment]
Hello ShiftedReality,

As you notcied already we got game cover's on our system and we are going to add that function in future realases.

Best Regards,
DevTeam

**Comment by juliankoehn** [comment]
+1

**Comment by Daddaaff** [comment]
+1

**Comment by eythormani** [comment]
+1

**Comment by codeswholesale** [comment]
Hello there!

I am happy to inform you that now you are able to get game covers using our RestAPI.

Best Regards,
DevTeam
