### ISSUE TITLE
CreateOrder should return the order id, too.

### ISSUE THREAD

**Issue by aedogroup** [codeswholesale/codeswholesale-sdk-php#6]
CreateOrder really should return the order id, for bookkeeping purposes. I don't see any reason why it is not included at the moment.

**Comment by codeswholesale** [comment]
Hello,

You can easly get orderId. Please take a look on code below:

 foreach ($order->getItems() as $item) {

     $cwProduct =\CodesWholesale\Resource\Product::get($cwProductId);

     $codes = \CodesWholesale\Resource\Order::createBatchOrder($cwProduct,    array('quantity' => $qty));

  $cwOrderId = $codes->getOrderId();

}

Variable $codes will return for you your orderId. Hope it helps ;)

Maciej

**Comment by aedogroup** [comment]
There is no such method/function in Resource/Code.php ;(

**Comment by aedogroup** [comment]
Am I missing something, or what?

**Comment by fefrik** [comment]
Hello,
 It is not about Resource/Code but about Resource/CodeList.php ;-) 

Anyway, this method $codes->getOrderId() return object orderID like XXXXX-XXXXX-XXXXX-XXXXX, but I would like to get invoice number for bookkeeping.

Is it possible to implement or add new method for those purposes? 

Thank you
